version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "172.25.30.77:80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./openvpn-admin-html:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - "php-fpm"

  php-fpm:
    build: php/
    volumes:
      - /var/www/openvpn-admin:/var/www

  mariadb:
    image: mariadb:10.5.19
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "172.19.0.1:3307:3306"


#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=1722.19.0.1
#      - PMA_PORT=3307
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=123123
#    ports:
#      - "172.25.30.77:8080:80"
#    links:
#      - "nginx"
#      - "mariadb"
