version: '3.9'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "172.19.0.1:80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./openvpn-admin-html:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - "php-fpm"
    networks:
      - network

  php-fpm:
    build: php/
    volumes:
      - ./openvpn-admin-html:/var/www
    networks:
      - network

  mariadb:
    image: mariadb:10.5.19
    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "172.19.0.1:3307:3306"
    networks:
      - network

  openvpn-monitor:
    image: ruimarinho/openvpn-monitor
    restart: always
    environment:
      - OPENVPNMONITOR_DEFAULT_DATETIMEFORMAT="%%d/%%m/%%Y"
      - OPENVPNMONITOR_DEFAULT_LATITUDE=-6.2
      - OPENVPNMONITOR_DEFAULT_LOGO=
      - OPENVPNMONITOR_DEFAULT_LONGITUDE=120
      - OPENVPNMONITOR_DEFAULT_MAPS=True
      - OPENVPNMONITOR_DEFAULT_MAPSHEIGHT=600
      - OPENVPNMONITOR_DEFAULT_SITE=
      - OPENVPNMONITOR_SITES_0_ALIAS="OpenVPN Office"
      - OPENVPNMONITOR_SITES_0_HOST=172.25.30.77
      - OPENVPNMONITOR_SITES_0_NAME="OpenVPN Office"
      - OPENVPNMONITOR_SITES_0_PORT=8991
      - OPENVPNMONITOR_SITES_0_SHOWDISCONNECT=True
      - OPENVPNMONITOR_SITES_1_ALIAS="Server 2 Server"
      - OPENVPNMONITOR_SITES_1_HOST=172.25.30.77
      - OPENVPNMONITOR_SITES_1_NAME="Server 2 Server"
      - OPENVPNMONITOR_SITES_1_PORT=8992
    ports:
      - "172.19.0.1:82:80"
    networks:
      - network

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=1722.19.0.1
#      - PMA_PORT=3307
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=123123
#    ports:
#      - "172.19.0.1:8080:80"
#    links:
#      - "nginx"
#      - "mariadb"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "172.19.0.1:53:53/tcp"
      - "172.19.0.1:53:53/udp"
      - "10.26.0.1:53:53/tcp"
      - "10.26.0.1:53:53/udp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "172.19.0.1:81:80/tcp"
    environment:
      TZ: 'Asia/Jakarta'
      WEBPASSWORD: 'adm1np!holes'
#      PIHOLE_DNS_1: '172.16.0.61'
#      PIHOLE_DNS_2: '172.16.0.62'
#      PIHOLE_DNS_3: '212.117.62.66'
#      PIHOLE_DNS_: '172.16.0.62;172.16.0.61;212.117.62.66'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole-data/etc-pihole:/etc/pihole'
      - './pihole-data/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
      - CAP_NET_ADMIN
      - CAP_CHOWN
      - NET_BIND_SERVICE
      - NET_RAW
    restart: unless-stopped
    networks:
      - network



networks:
  network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
